controller_list:
  - name: PositionJointInterface2_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - iiwa2_joint_1
      - iiwa2_joint_2
      - iiwa2_joint_3
      - iiwa2_joint_4
      - iiwa2_joint_5
      - iiwa2_joint_6
      - iiwa2_joint_7
      
      
